name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        include:
          - service: "Flight API"
            image-name: "flight-api-latest"
          - service: "authentication"
            image-name: "auth-latest"
          - service: "OrderAPI"
            image-name: "OrderAPI-Latest"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Docker Image
      run: docker build -t abdulqal/${{ matrix.image-name }} "./${{ matrix.service }}"

    - name: Log in to Docker Hub
      env:
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u abdulqal --password-stdin

    - name: Push Docker Image
      run: docker push abdulqal/${{ matrix.image-name }}
