name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          LINTER_RULES_PATH: .linter-configs
          JAVA_FILE_NAME: checkstyle.xml
          LANGUAGE: "java,javascript,typescript"
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_GITLEAKS: true


  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - Flight API
          - authentication
          - OrderAPI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests for ${{ matrix.service }}
        run: mvn test --file "${{ matrix.service }}/pom.xml"

      - name: Build ${{ matrix.service }}
        run: mvn clean package --file "${{ matrix.service }}/pom.xml"
